config/routes.rb
Rails.application.routes.draw do
  root 'accounts#index'
  devise_for :users

  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  validates :balance, numericality: { greater_than_or_equal_to: 25, message: "must be at least $25 to create account"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :accounts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update]

  def index
    @accounts = current_user.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      flash[:success] = "Account Created"
      redirect_to accounts_path
    else
      flash[:error] = "Error: #{@account.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
  end

  private
    def set_account
      @account = current_user.accounts.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %> </h2>
<hr />
<%= link_to 'Add Account', new_account_path %>
<h3>Your Accounts</h3>
<ul>
  <% @accounts.each do |a| %>
    <li>
      <%= a.name %> - $<%= a.balance %>
    </li>
  <% end %>
</ul>

app/views/accounts/new.html.erb
<h1>Add Account</h1>
<%= form_for @account do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :balance %>
  <%= f.text_field :balance, type: 'number', min: 0 %>
  <br />
  <%= f.submit %>
<% end %>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstBank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>